Repository projectsyn/component-metallb, pull requests merged in 2022-04, with the labels that each got.

#13 Change helm release_name to name
  class/defaults.yml
  class/metallb.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: dependency

#14 Remove namespace post filter
  class/metallb.yml
Labels: change

#15 Fix tenant name reclass references
  class/defaults.yml
Labels: bug

#16 Enable golden tests for metallb
  .sync.yml
Labels: change

#18 Add default variables for ModuleSync
  .sync.yml
Labels: enhancement

#20 Switch to official helm chart
  class/defaults.yml
  class/metallb.yml
  docs/modules/ROOT/pages/how-tos/upgrade-1.x-to-2.x.adoc
  docs/modules/ROOT/pages/index.adoc
  jsonnetfile.json
  tests/golden/defaults/metallb/metallb/10_metallb_helmchart/metallb/templates/controller.yaml
  tests/golden/defaults/metallb/metallb/10_metallb_helmchart/metallb/templates/psp.yaml
  tests/golden/defaults/metallb/metallb/10_metallb_helmchart/metallb/templates/rbac.yaml
  tests/golden/defaults/metallb/metallb/10_metallb_helmchart/metallb/templates/service-accounts.yaml
  tests/golden/defaults/metallb/metallb/10_metallb_helmchart/metallb/templates/speaker.yaml
Labels: enhancement
